### ISSUE TITLE
[Project Management] Sprint Review Notes

### ISSUE THREAD

**Issue by aolite** [Menuing/menuing-api#2]
Well done with the sprint review and retrospective documents. Please consider some recomendations from yesterday (to complement your list): 

|Recomendation| Description |
|---|---|
|Req 1| Decidir como implementar la vista de las alergias. Los datos estarán en el servidor web.|
|Req 2| Informar bien de la información personal y su tratamiento|
|Req 3| En la parte de contactar, implementar la vista para mandar el mail. |
|Req 4| El número de telefono choca dentro del "User Profile". El sentido es para validar los nutricionistas. |
|Req 5| Definir el proceso de lista de la compra. Está confuso. |
|Req 6| La gestión de los precios es un handicap. Un aspecto a tener en cuenta es hacer una escala de búsqueda (barato, medio, caro).|

**Comment by mrg20** [comment]
Thank you, we will add the recommendations 2, 3 and 4 into the Sprint Review document (Client improvements part). As for the other recommendations, the number 5 and 6 are already written and the recommendation 1 will be taken into account when preparing the MA algorithm.
